---
title: "GVA_Analysis_Final"
author: "Jennifer Fortunato"
date: "7/27/2020"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r R packages needed}

library(lme4)
library(lmerTest)
library(tidyverse)
library(broom.mixed)
library(rptR)

```

```{r Data and score conversion}

#Load Data
GVA <- read.csv("C:/Users/jaf13/Desktop/Earley Lab/Experiments/Genetic Variation in Aggression (GVA)/Analysis/GVA_R_Data.csv")
View(GVA)
str(GVA)

#Make factors
GVA$Age <- as.factor(GVA$Age)
GVA$Genotype <- as.factor(GVA$Genotype)
GVA$Video <- as.factor(GVA$Video)
GVA$Time <- as.factor(GVA$Time)
GVA$Observer <- as.factor(GVA$Observer)
GVA$Individual_ID <- as.factor(GVA$Individual_ID)

```

## Genotype {.tabset}

### Both Ages

```{r Models}

#Genotype model
lm1 <- lmer((Aggression + 1)^(1/3) ~ Age +  Age/Time + (1|Genotype), data = GVA, REML = TRUE) #The slash partions out each age into the two times
summary(lm1)
tidy(lm1) #Pretty table


#Fixed Effects model
lm2 <- lm((Aggression + 1)^(1/3) ~ Age + Age/Time, data = GVA)
summary(lm2)
tidy(lm2)


#Compare Genotype Model with Fixed Effect Model
anova(lm1, lm2)

#Get Variance Components
vc1 <- VarCorr(lm1) 
print(vc1,comp=c("Variance","Std.Dev."),digits=2)

#Calculate Heritability from numbers printed in above code 

0.025/(0.025 + 0.367)

#Standard Error Estimate (lm1) [also gives heritability]
rpt_lm1 <-  rptGaussian((Aggression + 1)^(1/3) ~ Age +  Age/Time + (1|Genotype), "Genotype", data = GVA, CI = 0.95, nboot = 1000)

rpt_lm1
```


### Juveniles
```{r}
#Subset GVA data to just juveniles
GVA_juv <- subset(GVA, Age == "J")
GVA_juv
#Genotype(juvenile) model
lm1_juv <- lmer((Aggression + 1)^(1/3) ~ Time + (1|Genotype), data = GVA_juv, REML = TRUE)
summary(lm1_juv)
tidy(lm1_juv) #Pretty table

#Fixed Effects (juvenile) model
lm2_juv <- lm(Aggression ~ Time, data = GVA_juv)
summary(lm2_juv)
tidy(lm2_juv) #Pretty table

#Compare Genotype Model with Fixed Effect Model
anova(lm1_juv, lm2_juv)

#Get Variance Components
vc1_juv <- VarCorr(lm1_juv) 
print(vc1_juv,comp=c("Variance","Std.Dev."),digits=2)

#Calculate Heritability from numbers printed in above code
0.085/(0.085 + 0.539)

#Standard Error Estimate (lm1_juv)
rpt_lm1_juv <-  rptGaussian((Aggression + 1)^(1/3) ~ Time + (1|Genotype), "Genotype", data = GVA_juv, CI = 0.95, nboot = 1000)

rpt_lm1_juv
```

### Adults

```{r}
#Subset GVA data to just Adults
GVA_adult <- subset(GVA, Age == "A")
View(GVA_adult)

#Genotype(adult) model
lm1_adult <- lmer((Aggression + 1)^(1/3) ~ Time + (1|Genotype), data = GVA_adult, REML = TRUE)
summary(lm1_adult)
tidy(lm1_adult) #Pretty table


#Fixed Effects(adult) model
lm2_adult <- lm((Aggression + 1)^(1/3) ~ Time, data = GVA_adult)
summary(lm2_adult)

#Compare Genotype(adult) Model with Fixed Effect(adult) Model
anova(lm1_adult, lm2_adult)

#Get Variance Components
vc1_adult <- VarCorr(lm1_adult) 
print(vc1_adult,comp=c("Variance","Std.Dev."),digits=2)

#Calculate Heritability from numbers printed in above code

0.0071/(0.0071 + 0.1573)

#Standard Error Estimate (lm1_adult)
rpt_lm1_adult <-  rptGaussian((Aggression + 1)^(1/3) ~ Time + (1|Genotype), "Genotype", data = GVA_adult, CI = 0.95, nboot = 1000)

rpt_lm1_adult
```

## Genotype by Age {.tabset}

### Genotype-by-Age
```{r}
#Full Model 
lm3 <- lmer((Aggression + 1)^(1/3) ~ Age + Age/Time + (1|Genotype) + (Age|Genotype), data = GVA, REML = TRUE) 
beta <- coef(lm3)$Genotype
colnames(beta) <- c("intercept", "slope")
beta
summary(beta)
summary(lm3)
tidy(lm3)
logLik_lm3 <- logLik(lm3, REML= TRUE)

#Full Model 
lm3.1 <- lmer((Aggression + 1)^(1/3) ~ Age+ Age/Time + (Age|Genotype), data = GVA) 
beta <- coef(lm3)$Genotype
colnames(beta) <- c("intercept", "slope")
beta
summary(beta)

#Genotype Model
lm1 <- lmer((Aggression + 1)^(1/3) ~ Age + Age/Time + (1|Genotype), data = GVA, REML = TRUE)
summary(lm1)
tidy(lm1)
logLik_lm1 <- logLik(lm1, REML= TRUE)

#Compare Full Model with Genotype Model
anova(lm3, lm1)

#Get Variance Components from Full Model
vc2 <- VarCorr(lm3) 
print(vc2,comp=c("Variance","Std.Dev."),digits=3)

#Calculate Heritability from numbers printed in above code*GET STANDARD ERROR ESTIMATES*
0.04361/(0.04361 + 0.00275 + 0.34703)

#Standard Error Estimate (lm3)
rpt_lm3 <-  rptGaussian((Aggression + 1)^(1/3) ~ Age + Age/Time +  (Age|Genotype), "Genotype", data = GVA, CI = 0.95, nboot = 1000)

rpt_lm3

```

### slopes
```{r}
slopes <- ranef(lm3.1)
slopes
?coef
GVA$coef[GVA$Genotype=="BWS21"] <- -0.31236143
GVA$coef[GVA$Genotype=="CRWL1"] <- 0.09098647
GVA$coef[GVA$Genotype=="EPP3"] <- 0.20887351
GVA$coef[GVA$Genotype=="EPP5"] <- -0.24984096
GVA$coef[GVA$Genotype=="IRP4-9"] <- -0.33032254
GVA$coef[GVA$Genotype=="LK4"] <- 0.09291946
GVA$coef[GVA$Genotype=="OY6"] <- 0.04501997
GVA$coef[GVA$Genotype=="RHL3-14"] <- .45472553

lmer(coef ~ ((Aggression+1)^(1/3)) + (1|Genotype) , data = GVA, REML=TRUE)

```

## Individual Analysis {.tabset}

### Individual - All
```{r}
#Individual Model
lm4 <- lmer((Aggression + 1)^(1/3) ~ Age +  Age/Time + (1|Individual_ID) , data = GVA)
summary(lm4)
tidy(lm4)
logLik_lm4 <- logLik(lm4, REML= TRUE)
logLik_lm4
#Fixed Effect Model
lm2 <- lm((Aggression + 1)^(1/3) ~ Age + Age/Time , data = GVA)
summary(lm2)
tidy(lm2)
logLik_lm2 <- logLik(lm2, REML= TRUE)

#Compare 4 and 5 (Is there among individual variation b/c you are taking indvidual out of the equation)
anova(lm4, lm2)

#Variance for lm4 
vc3 <- VarCorr(lm4) 
print(vc3,comp=c("Variance","Std.Dev."),digits=3)

#Repeatability for lm4
0.0774/ (0.0774 + 0.3126)
 

#Standard Error Estimate (lm4)
rpt_lm4 <- rptGaussian((Aggression + 1)^(1/3) ~ Age +  Age/Time + (1|Individual_ID), "Individual_ID" , data = GVA, CI = 0.95, nboot=1000)

rpt_lm4
```



###juvenile Individuals
```{r}
lm4_juv <- lmer((Aggression + 1)^(1/3) ~ Time + (1|Individual_ID) , data = GVA_juv)
summary(lm4_juv)
tidy(lm4_juv)
logLik_lm4_juv <- logLik(lm4_juv, REML= TRUE)

lm2_juv <- lm((Aggression + 1)^(1/3) ~ Time , data = GVA_juv)
summary(lm2_juv)
tidy(lm2_juv)
logLik_lm2_juv <- logLik(lm2_juv, REML= TRUE)

anova(lm4_juv, lm2_juv)

#Variance for lm4_juv
vc3_juv <- VarCorr(lm4_juv) 
print(vc3_juv,comp=c("Variance","Std.Dev."),digits=3)

#Repeatability for juveniles
0.307/(0.307+0.301)

#Standard Error Estimate (lm4_juv)
rpt_lm4_juv <- rptGaussian((Aggression + 1)^(1/3) ~ Time + (1|Individual_ID) , "Individual_ID" , data = GVA_juv, CI = 0.95, nboot=1000)

rpt_lm4_juv
```

###Adult Individuals
```{r}
lm4_adult <- lmer((Aggression + 1)^(1/3) ~ Time + (1|Individual_ID) , data = GVA_adult)
summary(lm4_adult)
tidy(lm4_adult)
logLik_lm4_adult <- logLik(lm4_adult, REML= TRUE)

lm2_adult <- lm((Aggression + 1)^(1/3) ~ Time , data = GVA_adult)
summary(lm2_adult)
tidy(lm2_adult)
logLik_lm2_adult <- logLik(lm2_adult, REML= TRUE)

anova(lm4_adult, lm2_adult)

#Variance for lm4_adult
vc3_adult <- VarCorr(lm4_adult) 
print(vc3_adult,comp=c("Variance","Std.Dev."),digits=3)

#Repeatability for adult
0.0553/(0.0553+0.1074)

#Standard Error Estimate (lm4_adult)
rpt_lm4_adult <- rptGaussian((Aggression + 1)^(1/3) ~ Time + (1|Individual_ID) , "Individual_ID" , data = GVA_adult, CI = 0.95, nboot=1000)

rpt_lm4_adult
```

### Individual-by-Age
```{r}
#Full Individual Model
lm5 <- lmer((Aggression + 1)^(1/3) ~ Age +  Age/Time + (1|Individual_ID) + (Age|Individual_ID), data = GVA, REML = TRUE)
summary(lm5)
tidy(lm5)
logLik_lm5 <- logLik(lm5, REML = TRUE)

lm5_IA <- lmer((Aggression + 1)^(1/3) ~ Age +  Age/Time +  (1|Age:Individual_ID), data = GVA, REML = TRUE)
summary(lm5_IA)

#Individual Model
lm4 <- lmer((Aggression + 1)^(1/3) ~ Age +  Age/Time + (1|Individual_ID), data = GVA, REML = TRUE)
summary(lm4)
tidy(lm4)
logLik_lm4 <- logLik(lm4, REML= TRUE)

#chi-square
2*(logLik_lm4-logLik_lm5)

#https://www.graphpad.com/quickcalcs/pvalue1.cfm to get p-value from chi square value (degrees of freedom will be 1!)

#compare 4 and 6 (Slope because you are taking age out of the Equation and not Individual)

anova(lm5, lm4)

#Variance for lm6 
vc5 <- VarCorr(lm5) 
print(vc5,comp=c("Variance","Std.Dev."),digits=3)

#Repeatability for lm6 
0.182/ (0.182 + 0.000 + 0.203) #47% of the variation in slopes is due to among individual differences

rpt_lm5_IA <- rptGaussian((Aggression + 1)^(1/3) ~ Age +  Age/Time +  (Age|Individual_ID) , "Individual_ID" , data = GVA, CI = 0.95, nboot=1000)

rpt_lm5_IA
```

### Slopes vs Indivdual Aggression
```{r}
lm5.1 <- lmer((Aggression + 1)^(1/3) ~ Age +  Age/Time +  (Age|Individual_ID), data = GVA, REML = TRUE)
summary(lm5.1)
indiv_slope <- ranef(lm5.1)
indiv_slope
view(GVA)
GVA$Indiv_Slope[GVA$Individual_ID=="29810"] <- -0.049168143
GVA$Indiv_Slope[GVA$Individual_ID=="29850"] <-  0.154756921
GVA$Indiv_Slope[GVA$Individual_ID=="29851"] <- -0.219727339
GVA$Indiv_Slope[GVA$Individual_ID=="29852"] <- -0.065109769
GVA$Indiv_Slope[GVA$Individual_ID=="29857"] <-  0.024589268
GVA$Indiv_Slope[GVA$Individual_ID=="29875"] <- -0.089348377
GVA$Indiv_Slope[GVA$Individual_ID=="29876"] <-  1.447564824
GVA$Indiv_Slope[GVA$Individual_ID=="29892"] <- -0.041545015
GVA$Indiv_Slope[GVA$Individual_ID=="29893"] <-  1.258066535
GVA$Indiv_Slope[GVA$Individual_ID=="29896"] <- -0.488460673
GVA$Indiv_Slope[GVA$Individual_ID=="29902"] <-  1.102520636
GVA$Indiv_Slope[GVA$Individual_ID=="29903"] <-  0.963274286
GVA$Indiv_Slope[GVA$Individual_ID=="29904"] <-  0.727472301
GVA$Indiv_Slope[GVA$Individual_ID=="29905"] <- -0.127531601
GVA$Indiv_Slope[GVA$Individual_ID=="29921"] <-  0.034121895
GVA$Indiv_Slope[GVA$Individual_ID=="29922"] <- -0.377735290
GVA$Indiv_Slope[GVA$Individual_ID=="29923"] <- -0.071747806
GVA$Indiv_Slope[GVA$Individual_ID=="29924"] <-  0.191117168
GVA$Indiv_Slope[GVA$Individual_ID=="29925"] <-  0.829425195
GVA$Indiv_Slope[GVA$Individual_ID=="29926"] <-  0.048943065
GVA$Indiv_Slope[GVA$Individual_ID=="29927"] <-  1.295150196
GVA$Indiv_Slope[GVA$Individual_ID=="29984"] <-  0.403277283
GVA$Indiv_Slope[GVA$Individual_ID=="30027"] <-  0.649987618
GVA$Indiv_Slope[GVA$Individual_ID=="30063"] <- -0.649588962
GVA$Indiv_Slope[GVA$Individual_ID=="30064"] <- -1.092806516
GVA$Indiv_Slope[GVA$Individual_ID=="30066"] <- -0.146750046
GVA$Indiv_Slope[GVA$Individual_ID=="30095"] <- -1.119666766
GVA$Indiv_Slope[GVA$Individual_ID=="30122"] <- -0.023013989
GVA$Indiv_Slope[GVA$Individual_ID=="30132"] <-  0.102693044
GVA$Indiv_Slope[GVA$Individual_ID=="30146"] <- -0.181668133
GVA$Indiv_Slope[GVA$Individual_ID=="30147"] <-  0.126671747
GVA$Indiv_Slope[GVA$Individual_ID=="30218"] <- -0.174392367
GVA$Indiv_Slope[GVA$Individual_ID=="30219"] <- -1.113849148
GVA$Indiv_Slope[GVA$Individual_ID=="30222"] <- -0.105174224
GVA$Indiv_Slope[GVA$Individual_ID=="30132"] <-  0.102693044
GVA$Indiv_Slope[GVA$Individual_ID=="30146"] <- -0.181668133
GVA$Indiv_Slope[GVA$Individual_ID=="30147"] <-  0.126671747
GVA$Indiv_Slope[GVA$Individual_ID=="30218"] <- -0.174392367
GVA$Indiv_Slope[GVA$Individual_ID=="30219"] <- -1.113849148
GVA$Indiv_Slope[GVA$Individual_ID=="30222"] <- -0.105174224
GVA$Indiv_Slope[GVA$Individual_ID=="30223"] <-  0.036151247
GVA$Indiv_Slope[GVA$Individual_ID=="30224"] <- -0.153661327
GVA$Indiv_Slope[GVA$Individual_ID=="30228"] <-  0.046060183
GVA$Indiv_Slope[GVA$Individual_ID=="30230"] <-  0.069123810
GVA$Indiv_Slope[GVA$Individual_ID=="30232"] <-  0.164693775
GVA$Indiv_Slope[GVA$Individual_ID=="30233"] <- -0.201780165
GVA$Indiv_Slope[GVA$Individual_ID=="30234"] <- -0.098525444
GVA$Indiv_Slope[GVA$Individual_ID=="30235"] <- -0.192214503
GVA$Indiv_Slope[GVA$Individual_ID=="30236"] <-  0.457098065
GVA$Indiv_Slope[GVA$Individual_ID=="30256"] <- -0.099669951
GVA$Indiv_Slope[GVA$Individual_ID=="30300"] <- -0.358130773
GVA$Indiv_Slope[GVA$Individual_ID=="30301"] <- -0.710791714
GVA$Indiv_Slope[GVA$Individual_ID=="30326"] <- -0.641485598
GVA$Indiv_Slope[GVA$Individual_ID=="30371"] <- -0.099538047
GVA$Indiv_Slope[GVA$Individual_ID=="30375"] <-  0.037282618
GVA$Indiv_Slope[GVA$Individual_ID=="30376"] <-  1.105140240
GVA$Indiv_Slope[GVA$Individual_ID=="30422"] <- -0.190388636
GVA$Indiv_Slope[GVA$Individual_ID=="30435"] <- -0.185908072
GVA$Indiv_Slope[GVA$Individual_ID=="30449"] <-  0.558882697
GVA$Indiv_Slope[GVA$Individual_ID=="30477"] <- -0.442171571
GVA$Indiv_Slope[GVA$Individual_ID=="30566"] <- -0.368805421 
GVA$Indiv_Slope[GVA$Individual_ID=="30567"] <- -0.116137779
GVA$Indiv_Slope[GVA$Individual_ID=="30568"] <- -0.194898367
GVA$Indiv_Slope[GVA$Individual_ID=="30641"] <- -0.209873369
GVA$Indiv_Slope[GVA$Individual_ID=="30642"] <- -0.756304974
GVA$Indiv_Slope[GVA$Individual_ID=="30643"] <- -0.384619411
GVA$Indiv_Slope[GVA$Individual_ID=="30644"] <- -0.394947808
GVA$Indiv_Slope[GVA$Individual_ID=="30801"] <-  0.008666674
GVA$Indiv_Slope[GVA$Individual_ID=="30822"] <-  0.094405804
GVA$Agg_scale <- scale(GVA$Aggression, center = TRUE, scale = TRUE)
GVA$Indiv_scale <- scale(GVA$Indiv_Slope, center = TRUE, scale = TRUE)

library("scales")
GVA$Agg_rescale <- rescale(GVA$Aggression, to=c(-1,1))
GVA$Indiv_Slope_rescale <- rescale(GVA$Indiv_Slope, to=c(-1,1))
view(GVA)
GVA$AggressionJuv[GVA$Age=="J"] <-  GVA$Agg_scale
GVA$AggressionJuv[GVA$Age=="A"] <-  NA
GVA$AggressionJuv <- as.numeric(GVA$AggressionJuv)

agg_slopes <- lmer(Indiv_scale ~ AggressionJuv + (1|Genotype), data= GVA, REML = TRUE)
summary(agg_slopes)
plot(agg_slopes)

ggplot(aes(AggressionJuv, Indiv_Slope_rescale), data = GVA)+
  geom_point()+
  stat_smooth(method=lm)

```
